name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Cài đặt Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Checkout mã nguồn
      - name: Check out code
        uses: actions/checkout@v4

      # Kiểm tra định dạng mã
      - name: Format code
        run: gofmt -l . | grep . && exit 1 || exit 0

      # Chạy linter
      - name: Run linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      # Chạy unit tests
      - name: Run tests
        run: go test ./... -v -cover

      # Biên dịch ứng dụng
      - name: Build
        run: go build -v ./...

      # Tạo Docker image
      - name: Build Docker image
        run: docker build -t go-rest-api:latest .

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Đẩy Docker image lên Docker Hub
      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag go-rest-api:latest ${{ secrets.DOCKER_USERNAME }}/go-rest-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/go-rest-api:latest